person:
  crayon:
    tool:
      log:
        interceptor:
          enable: true
      exception:
        handler:
          constraint:
            enable: false
          custom:
            enable: false
      captcha:
        check:
          filter:
            url-patterns: