person:
  crayon:
    tool:
      log:
        interceptor:
          order: 999
          enable: true
          format-template: '{} | {} | {} | {} ms ===> {}'
          add-path-patterns: /**
          exclude-path-patterns:
      rate-limiter:
        interceptor:
          order: 999
          enable: false
          add-path-patterns: /**
          exclude-path-patterns:
      exception:
        handler:
          constraint:
            enable: false
          custom:
            enable: false
      captcha:
        check:
          filter:
            url-patterns: /*
spring:
  messages:
    basename: messages
