
person:
  crayon:
    tool:
      rate-limit:
        enable: true
        interceptor:
          add-path-patterns: /**
      log:
        enable: true
        interceptor:
          format-template: "{0} | {1} | {2} | {3}ms"
          add-path-patterns: /**
      exception:
        handler:
          constraint:
            enable: true
            code: 400
            message: Bad Request
          custom:
            enable: true
      captcha:
        check:
          filter:
            url-patterns: /*
          enable: true

server:
  servlet:
    context-path: /crayontool-test
  port: 28080