person:
  crayon:
    tool:
      rate-limiter:
        interceptor:
          add-path-patterns: /**
          enable: true
      log:
        interceptor:
          enable: true
          format-template: '{0} | {1} | {2} | {3}ms'
          add-path-patterns: /**
      exception:
        handler:
          constraint:
            enable: true
          custom:
            enable: true
      captcha:
        check:
          enable: true
          filter:
            url-patterns: /*

server:
  servlet:
    context-path: /crayontool-test